### ISSUE TITLE
New Tag System

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#100]
- People could create new Tags
- Extend the list of tags available to the whole list of ReGen Tags. https://docs.google.com/document/d/1xCtQ_HvI1Fow8A6MyIZGLHeHyReOhL3OmojGdyKfDUk/edit?usp=sharing

---

Throughout the alignment performed on the demand Marcelo shared with us that it would be necessary to discuss with the development team what would make sense and impact less on the development of Ootopia's MVP, and after discussing with Claudio on Jul 7 it was aligned that the fastest and most objective way of this demand would be to update the list of available tags with the list that was sent to us in the document.

**Comment by VictorCampelo** [comment]
### Atualização:

Query de atualização de tags finalizada.

### Pendência:

Falta testar a execução de query e avaliar o impacto de sua execução quanto a normalizada do sistema, pois a query foi modelada num formato onde todas as interests_tags atuais teria o campo “active” definido como false e, portanto, as novas tags seriam adicionadas.

**Comment by VictorCampelo** [comment]
PR for review: https://github.com/OOTOPIA/ootopia-api/pull/63

### What was done:
- Old tags were deactivated and the new tags were added according to the specified document.
