### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#101]
- Pay attention in the properties from database

**Comment by biliboss** [comment]
![image](https://user-images.githubusercontent.com/1461583/119578941-d1a49b00-bd93-11eb-88eb-c4607660da52.png)

**Comment by AtsKotzen** [comment]
Main account @ootopia.org
Localized content in portuguese ootopia.br

https://discord.com/channels/717601425630429197/839987190829678663/869581718045220925
