### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#104]
- When I attempt to login, the system doesn't give me an error message or login. Android Version 0.0.23
- I forgot my password and can't recover it because the bottom to recover the password is not working.

**Comment by marcelobohrerid** [comment]
Hi Gabriel, here the video showing the problem to do the login/recover the password.
https://youtu.be/Z0hODwUE1l4

**Comment by biliboss** [comment]
Thanks for the video @marcelobohrerid, could you also share with us the password used in this test? With this, we could debug the code to find what's happening.

**Comment by marcelobohrerid** [comment]
Hi Gabriel, yesterday I reinstalled to App for version.33 The problem with the recovering password is not solved yet! 
Therefore, I still can't access the app with my ootopia account because I don't know my password!!!

**Comment by biliboss** [comment]
Hey @marcelobohrerid you could follow the queue of tasks here in this [link](https://github.com/OOTOPIA/ootopia-app/projects/1)  password retrieval is far in our roadmap, feel free to move it in queue.

The fastest way to solve your issue right now, is creating a new account.

**Comment by marcelobohrerid** [comment]
I can't. The system says there is already an account with the email marcelo@ootopia.org
Can you please move this issue forward on the priority queue? I'd like to use/test the app with my ootopia account.

**Comment by biliboss** [comment]
Done it @marcelobohrerid. I started a thread to align UX on the issue #124. 

Also, I will ask for the team to reset the password directly on database 👈 @AndrewDiass , @claudiooliveira

**Comment by claudiooliveira** [comment]
Alright @biliboss , the password of marcelo@ootopia.org has been reset to 123456.
