### ISSUE TITLE
Recover password

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#124]
This video shows the problem to recover the password.
https://youtu.be/yqzNb7XgL8g

**Comment by biliboss** [comment]
@marcelobohrerid we can do something basic here, or you will create the UI for this?

Also a video about what we have in UI https://youtu.be/gW6gAGrgbz4 (in english for training 😅)

**Comment by marcelobohrerid** [comment]
Hi Gabriel, the UI for the notification about the resetting password procedures is on Figma.
You may notice that I changed the welcoming texts above. You can adjust it now or we can review everything just before translating everything to portuguese.
![Screenshot 2021-06-02 at 16 24 19](https://user-images.githubusercontent.com/83228193/120498870-de427800-c3bf-11eb-84f0-39e9a4568fb2.png)

**Comment by biliboss** [comment]
@AtsKotzen we will move this card after the integration with app. Or it's already done?
