### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#127]
@marcelobohrerid will prepare the animation of Splashscreen

---

### What should be done

@marcelobohrerid shared with us a video of the splashscreen that will be used in the Ootopia application. The animation should happen as soon as the application is opened.

The **.mov** file below is available for download

https://images.zenhubusercontent.com/341327321/0a8f67f6-95e3-49de-b05f-66e4a9db7f11/ootopia_splash_.mov

### Jira Card
https://devmagic.atlassian.net/browse/OOT-162

**Comment by biliboss** [comment]
@danillosantos, @claudiooliveira what's the better format of video to run on Splash Screen. @marcelobohrerid , needs this.

**Comment by biliboss** [comment]
@rasta team have an experience with this Tool https://lottiefiles.com/

**Comment by marcelobohrerid** [comment]
@danillosantos, @claudiooliveira I need this information to move forward with this topic.
When can you check this info and send it to me?

**Comment by biliboss** [comment]
@marcelobohrerid, @AtsKotzen knows someone that could help us here.

**Comment by AndrewDiass** [comment]
PR das alterações: feat: splash screen by AndrewDiass · Pull Request #198 · OOTOPIA/ootopia-app
