### ISSUE TITLE
Fixed Badges

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#128]
Even if fixed, would be great with have something.

Maybe associated with "invite code"

* Esse módulo será refatorado lá na frente. Vamos fazer o mais barato nesse momento. 
* Talvez adicionar um invite code na tela de cadastro

--- 

### Esse caso possui 3 "partes"
* Perfil do usuário (presente no épico https://app.zenhub.com/workspaces/ootopia-60b82d5c8990d7000f175d3f/issues/ootopia/ootopia-app/97 ): foi alinhado o comportamento da badge do perfil do usuário e que só aparece quando, na base de dados, o usuário possuir a badge "sower";

* Timeline (presente neste épico): Nas publicações dos usuários que possuem badges aparece um ícone da badge e, ao ser tocada, disparada um snackbar explicando para que serve e o usuário pode entrar em contato via e-mail ou ler mais;

* Invite Codes (presente no épico https://app.zenhub.com/workspaces/ootopia-60b82d5c8990d7000f175d3f/issues/ootopia/ootopia-app/205 ): O usuário poderá gerar um código e disponibilizar com outros usuários - quando utilizado no cadastro, o usuário automaticamente recebe a badge sower.

**Comment by marcelobohrerid** [comment]
We will need only one badge for the MVP, the Sower / Semeador badge.
Here comes the element. 
![icon badge sower.svg](https://images.zenhubusercontent.com/60bfad5cdf381123a6445d5b/04e5149c-b210-4126-a2b6-21dc77b10129)
