### ISSUE TITLE
Bug no carregamento de video - Android version #33

### ISSUE THREAD

**Issue by marcelobohrerid** [OOTOPIA/ootopia-app#129]
Screen record sobre o Bug no carregamento de video - Android version #33
https://youtu.be/JcNww27PxN0

**Comment by biliboss** [comment]
@marcelobohrerid right after we enabled your account, our backend got offline. So, I'll close this issue for now, and if you had this issue again we'll reopen it ok?

**Comment by biliboss** [comment]
@marcelobohrerid posted on discord

> @Gabriel Fonseca  sobre o Issue  #129. Ainda não tô conseguindo carregar/postar videos.
