### ISSUE TITLE
Disable Wallet features for MVP

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#133]
Request by @marcelobohrerid 
https://discord.com/channels/717601425630429197/778779840903249961/849665590108487690

**O que precisa ser feito?**

1. Remover os botões "add" e "send" money da parte de Wallet do perfíl do usuário.

**Comment by AndrewDiass** [comment]
PR das alteracoes: https://github.com/OOTOPIA/ootopia-app/pull/170

- [x] Remover os botões "add" e "send" money da parte de Wallet do perfil do usuário.

![Screen Shot 2021-06-28 at 21.28.11.png](https://images.zenhubusercontent.com/60be85f867611e1a3f0f5c60/3f61b488-5704-4e64-aef9-732f3f3137ac)
