### ISSUE TITLE
Terms should be inside App

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#134]
Rasta: Apple reprova se o termo não estiver dentro do app
---

For the app to be available on iOS the terms need to be inside the app. Currently the app redirects the user to the screen outside the app.

### What needs to be accomplished

![image.png](https://images.zenhubusercontent.com/60d9a19222b134d7fe8709b8/fec38730-aac1-4f17-9478-c5374d3a8307)

We will update the interaction so that the user can view the terms (the same ones used today on the site) into the app - we will replicate the same layout as the reference above, but it is also interesting to add a go back button below confirm (as secondary) that allows the user without the commitment to check I accept the terms of use.

Also, the confirm button is only active if all criteria (inputs and checkboxes) are fulfilled.

Translated with www.DeepL.com/Translator (free version)

**Comment by AndrewDiass** [comment]
PR com as alterações: https://github.com/OOTOPIA/ootopia-app/pull/189
