### ISSUE TITLE
Revisar transferência de OOZ por vídeo assistido

### ISSUE THREAD

**Issue by claudiooliveira** [OOTOPIA/ootopia-app#143]
Para não poluir o histórico da carteira do usuário, ao invés de fazer a transferência a cada requisição de vídeo assistido, avaliar a possibilidade de um cron.

**Comment by marcelobohrerid** [comment]
Concordo! 
De fato, cada ganho referente as ações de utilização do app não deve aparecer separadamente no Wallet / received.
Isso porque de acordo com as regras do game os créditos em OOz são acumulado ao longo do turno do jogo (24h). O usuário só recebe esses créditos se ele bater a sua meta diária. Nesse caso, irá aparecer na Wallet apenas um registro do crédito total recebido naquele dia. Na verdade serão 3 registros na Wallet por dia referentes ao game, o da meta individual, o da cidade e o da meta global.
Segue um print do design dos créditos na Wallet. (Figma)

Obs: O que é um cron.?
![Screenshot 2021-06-22 at 16.53.03.png](https://images.zenhubusercontent.com/60bfad5cdf381123a6445d5b/97770297-ca8c-46c6-8d67-692b558c94b0)
