### ISSUE TITLE
Post Photos on Timeline

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#145]
* Tratamento da imagem - cuidado com o armazenamento das imagens
* Rasta: S3 & Cloudfront
* Rasta: Caching de timeline no Cloudfront
* Rasta: Controle de expiração
* Pensar no CROP - Qual o melhor custo benefício. Como tirar fotos horizontal e vertical...
  * Usar o Instagram de benchmark
  * Horizontal e Vertical
  * Qual vai ser o melhor custo benefício
  * Procurar a melhor lib custo-benefício ou implementar o mínimo necessário

**Comment by biliboss** [comment]
![image.png](https://images.zenhubusercontent.com/60b82d2c50479622e89fa8ab/7454c4b3-86af-4084-81ef-f24d87ab6690)

Hey @marcelobohrerid. I noticed that we haven't added this Story here. But you need to confirm with @Florian-ootopia if it will be added or not to the MVP

**Comment by marcelobohrerid** [comment]
As I said, we need this function on the MVP to test what people will prefer to use, photos or pictures.
