### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#147]
This is a sample of Cambiatus Marketplace https://muda.cambiatus.io/invite/EWA9gW

We need to create the minimal experience of an Marketplace

![image.png](https://images.zenhubusercontent.com/60b82d2c50479622e89fa8ab/51a59d6f-6233-4f5c-adfc-9c20baad3de0)
![image.png](https://images.zenhubusercontent.com/60b82d2c50479622e89fa8ab/d517a61a-06bf-415a-9c1c-f3367e6eca81)

# Cambiatus Experience

Here is a video with the explanation of Cambiatus experience
https://share.vidyard.com/watch/Mohu8BuL4kSnSoTB9W9Uzi?

# Estimated Stories

1. Create an offer
1. View offer
1. View own offer
1. Remove an offer
1. Buy an Offer
    1. Should guarantee that buyer get the contact
    1. Should use the OOz transaction module
1. Notify user about the buy

**Comment by marcelobohrerid** [comment]
Isso parece uma tarefa colossal para incluir no MVP.
Deixaria no Icebox.

**Comment by biliboss** [comment]
@marcelobohrerid @Florian-ootopia we could talk about Marketplace here

**Comment by biliboss** [comment]
@marcelobohrerid, @luizeroo I had edited the description of this card with my experience with Cambiatus. It's just a rough analysis to see how much work do we have.
