### ISSUE TITLE
Integrate Photos with OOz with Distribution System

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#149]

**Comment by VictorCampelo** [comment]
### Progress

- When posting an image then the OOZ defined in the specification are assigned to the posting user's transaction list. The value assigned when making an image post is 15 OOZ. 

- Added enum for the image post reward.

- Refactoring was done when returning the posts that were not deleted. For this the deleted_at field was added, in the posts entity, which stores the date when a post was deleted. It is also responsible for controlling the return of only the posts that were not deleted.
