### ISSUE TITLE
[front/back] Add the timeline view time to the game

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#155]
### Context

Actions within the Ootopia system generate points, however there is a need to revise some point assignments and also add score distribution in the timeline view, both of these pending issues have been aligned with the  @claudiooliveira 

### Business Rules
https://docs.google.com/document/d/1kzUl-edlACQUIJdrm4Dc_mqNjxJhxVatrvO5dekUgik/edit

**Comment by claudiooliveira** [comment]
A parte de backend desse caso já foi realizada.
