### ISSUE TITLE
Explain to the users about the next release (city and global game)

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#165]
Jira card: https://devmagic.atlassian.net/browse/OOT-153

Images - Next Release/Learn More (Personal, City, Planetary)
![image.png](https://images.zenhubusercontent.com/60d9a19222b134d7fe8709b8/50e9aac5-47c6-48fa-9e44-6182797042ff)

### Context

1. When the user clicks the **Personal** icon for the first time, an explanation screen appears with Close and Learn More buttons
* Close: Closes the page and the user has no more access to it;
* Learn More: Takes the user to the Learning Tracks;

1.1 After that, when the user interacts with the Personal icon an animation is fired to show the data:
* Personal Goal;
* Accomplished;
* Partial Balance;

---

2. When the user clicks on the **City** icon it will always open an explanation screen with Close and Learn More buttons
* Close: Closes the page;
* Learn More: Takes the user to the Learning Tracks;

---

3. When the user clicks on the **Planetary** icon it will always open an explanation screen with Close and Learn More buttons
* Close: Closes the page;
* Learn More: Takes the user to the Learning Tracks;

**Comment by claudiooliveira** [comment]
@biliboss tem mais informações sobre este caso?

**Comment by biliboss** [comment]
@claudiooliveira mesmo sem implementar a função do game Cidade e Global, queremos deixar claro para as pessoas que no futuro haverá essa função.
