### ISSUE TITLE
Badge on timeline

### ISSUE THREAD

**Issue by luizeroo** [OOTOPIA/ootopia-app#207]
### What must be accomplished

Jira card: https://devmagic.atlassian.net/browse/OOT-199

All users who have the sower badge registered should have a badge appear next to their post in their posts. When other users interact with this icon a snackbar is triggered with the option to "learn more" or "contact us" (via email

![image.png](https://images.zenhubusercontent.com/60d9a19222b134d7fe8709b8/aa1ee6a7-ce0a-4c15-b9ea-0d68b142f050)

**Comment by VictorCampelo** [comment]
### Progress

- The list of badges associated with a user is being returned when requests are made to obtain information about the user and in the posts seen on the timeline the list of baggies is also being added.

### Video / Gif (situational)
- Example of .Json returns.

![image.png](https://images.zenhubusercontent.com/60f977889e3a381c85de954d/7116b88b-5ffe-451e-a5cb-4335f2bd865d)
