### ISSUE TITLE
We should see the OOz wallet of other Ootopians?

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#71]
We currently have the design definition of the "my" profile screen, we are also using the same layout for other Ootopians mates. Have that in mind, we should make the Wallet publicly visible to everyone?

**Comment by biliboss** [comment]
A copy of the message sent by Vini at Discord:

> glocalvr — Ontem às 22:06
> transparência é um dos valores seminais deste emergente movimento regenerativo planetário!! assim sendo ...

**Comment by marcelobohrerid** [comment]
I think it can come visible by defalut, but I recommend we give the user the right to set it invisible if he/she wants.

**Comment by biliboss** [comment]
It's a good option @marcelobohrerid, could you create the UI for this interaction?

**Comment by biliboss** [comment]
Florian said at meeting, that would be great if we could show how much OOZ went throw a user - show how much energy went through you: Highlighting for the world the quality of the node you are.

![Uploading image.png…]()

**Comment by marcelobohrerid** [comment]
Regarding Florian's suggestion. Let's save this for a future version, V2 perhaps. We have to keep things simple for the MVP to happen, right?

**Comment by biliboss** [comment]
> Regarding Florian's suggestion. Let's save this for a future version, V2 perhaps. We have to keep things simple for the MVP to happen, right?

Yeah, as blockchain will be public, I do not see why we would hide this info in our app. So I thought that we could close this issue and left all public in the first versions. We could do that @marcelobohrerid ?

**Comment by marcelobohrerid** [comment]
For the MVP we can leave the Wallet balance open for sure!

**Comment by biliboss** [comment]
Awesome. I will close this issue then.
