### ISSUE TITLE
Profile and Edit Profile

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#97]
https://discord.com/channels/717601425630429197/778779840903249961/842466256060678154

**Comment by marcelobohrerid** [comment]
Salve galera, segue a versão ajustada e atualizada da tela do perfil!
Dúvidas, sugestões é só falar.
![Screenshot 2021-06-25 at 14.19.57.png](https://images.zenhubusercontent.com/60bfad5cdf381123a6445d5b/0a7d6b3b-1c40-4df3-b217-e5616eaed039)
