### ISSUE TITLE
OOz Distribution System

### ISSUE THREAD

**Issue by biliboss** [OOTOPIA/ootopia-app#98]
About the actions that generates OOz

**Comment by biliboss** [comment]
After a user watch a full content on timeline, I thought that we could have an UX that makes clear to the user that he received some OOz by watching. What do you think @marcelobohrerid

**Comment by marcelobohrerid** [comment]
Gabriel, o arquivo com as infos atuais sobre as regras do Game e os respectivos crétidos em OOz se chama Regras do Jogo OOTOPIA App. https://docs.google.com/document/d/1kzUl-edlACQUIJdrm4Dc_mqNjxJhxVatrvO5dekUgik/edit?usp=sharing

Copio abaixo a tabela dos créditos em OOz em relação a utilização/engajamento no app.

**CRÉDITOS IN OOz**
Lista das ações que geram créditos em OOz (mineração). 
(Nota: o valor de créditos para cada ação há de ser revisado e reavaliado)

**Créditos gerados por assistir/aprender com os conteúdos**
Visualizar a time line ….….........… = 0,10 OOz por minuto
Assistir videos até o fim ….…....… = 0,20 OOz por minuto
Assistir Learning Track  ………..… = 2,00 OOz por minuto
Resposta correta do quiz …... 1 resposta = 2,00 OOz
(no V2) Compartilhar post ……………...…... 1,00 OOz
outra?

**Creditos para criadores de conteúdo**
Postar vídeo …………………….……… = 25,00 OOz por minuto
Postar foto ……………………....……...  = 15,00 OOz por post
Vídeo do criador sendo assistido …..... = 0,25 OOz por minuto
(no V2) Minha Learning Track sendo assistida ….. = 0,50 OOz por minuto
Receber wOOw ………………….….…. = 0,01 OOz por wOOw
outra?

**Comment by biliboss** [comment]
@marcelobohrerid I have a question in video for you.

https://share.vidyard.com/watch/q4cg1SA77w4y88F6EaQwse?

**Comment by marcelobohrerid** [comment]
Salve Gabriel,
Todas as ações dessa lista são formas de mineração, ou seja, todas receberão OOz do fundo abundante OOTOPIA no blockchain.

**Comment by claudiooliveira** [comment]
Hi @marcelobohrerid !

An internal question has arisen here about the user's personal goal.

The daily goal corresponds only to the OOZ generated using the app, that is, viewing the timeline/video, so the user will only receive this OOZ effectively if he hits the daily use goal (the time of use of the app that he established ).

But if someone sends him OOZ through a wOOw or swipes the widget to send reward, he gets that OOZ right away, right?

We had this doubt and the documentation was not clear at this point.

Thanks!

**Comment by marcelobohrerid** [comment]
Hi Claudio, 
That's right! 
When a user receives a gratitude reward, he gets that OOZ right away in his wallet.
Another rule that was missing in the Regras do Jogo document is about when the OOz earned just by watching the timeline are credited to the pre-wallet. I discussed it with Luiz and we came out to the conclusion that the best dynamics is to credit the OOz every time the user goes out of the timeline. For example, I am watching the timeline for 5 minutes, this creates 0,50 OOz. These OOz are credited to the pre-wallet only when I leave the timeline screen to go to another screen like the profile screen, the add content screen.
Then, when I return to the timeline screen the system begins to count the time again to calculate the OOz credit.
If you have any questions about it, ask Luiz.

**Comment by claudiooliveira** [comment]
Thank you @marcelobohrerid !
I have another question at the moment, to determine if the user achieved the daily goal should we add the timeline viewing time + the video viewing time or just consider the video watched time?

I ask this question because many times the user will end up generating OOZ while on the timeline and watching videos at the same time, which gives the feeling of duplicity.

**Comment by marcelobohrerid** [comment]
Claudio, non of these two options.
The time that is summed to meet the personal daily goal is the general time the user is using the app.
This means that the time starts counting when he/she opens the app (no matter what he/she is doing) and stops counting every time he/she exit the app.
